/**
 * @file lib/types.ts
 * Core domain types shared across the entire Salty application.
 *
 * These types mirror the Supabase database schema and the JSON structures
 * returned by the Gemini edge function. Any schema change (migration) should
 * be reflected here first so TypeScript surfaces the inconsistency.
 */

/**
 * A user's profile row from the `profiles` table.
 * Created automatically by a Supabase trigger on `auth.users` insert.
 */
export interface Profile {
  /** UUID — matches `auth.users.id`. */
  id: string;
  /** The email address used for magic-link login. */
  email: string;
  /** Optional display name set by the user. */
  display_name: string | null;
  /** The user's primary motivation for using Salty. */
  goal: 'save_money' | 'eat_healthy' | 'learn_to_cook' | 'save_time';
  /** Weekly grocery budget in USD. */
  weekly_budget: number;
  /** Self-reported cooking ability. */
  skill_level: 'beginner' | 'intermediate' | 'advanced';
  /** Active dietary restrictions that the AI must respect when generating meals. */
  dietary_restrictions: DietaryRestriction[];
  /** True once the user has completed all onboarding steps. */
  onboarding_complete: boolean;
  /** ISO 8601 timestamp — set by the database on insert. */
  created_at: string;
  /** ISO 8601 timestamp — updated automatically by a database trigger. */
  updated_at: string;
}

/**
 * All supported dietary restriction identifiers.
 * Must stay in sync with `VALID_DIETARY` in `lib/validation.ts` and the
 * CHECK constraint in `supabase/migrations/002_security_hardening.sql`.
 */
export type DietaryRestriction =
  | 'vegan'
  | 'vegetarian'
  | 'gluten_free'
  | 'dairy_free'
  | 'nut_free'
  | 'halal'
  | 'kosher';

/**
 * A single ingredient with its quantity, unit, and estimated cost.
 * Stored as JSONB in the `meals.ingredients` column.
 */
export interface Ingredient {
  /** Human-readable ingredient name (e.g. `'chicken breast'`). */
  name: string;
  /** Numeric or descriptive quantity (e.g. `'200'`, `'2 cups'`). */
  quantity: string;
  /** Unit of measurement (e.g. `'g'`, `'ml'`, `'tbsp'`). */
  unit: string;
  /** Estimated cost of this ingredient in USD. */
  estimated_cost: number;
}

/**
 * A single step in a recipe's instructions.
 * Stored as JSONB in the `meals.instructions` column.
 */
export interface InstructionStep {
  /** 1-based step number for display ordering. */
  step: number;
  /** Full text of the instruction. */
  text: string;
}

/**
 * A saved meal row from the `meals` table.
 * AI-generated meals have `is_ai_generated: true`; manually created meals have false.
 */
export interface Meal {
  /** UUID primary key. */
  id: string;
  /** UUID of the owning user. */
  user_id: string;
  /** Display name of the meal. */
  name: string;
  /** Optional description / summary. */
  description: string;

  /** Structured ingredient list. */
  ingredients: Ingredient[];
  /** Ordered cooking instructions. */
  instructions: InstructionStep[];
  /** Total calories per serving. */
  calories: number;
  /** Protein in grams per serving. */
  protein_g: number;
  /** Carbohydrates in grams per serving. */
  carbs_g: number;
  /** Fat in grams per serving. */
  fat_g: number;
  /** Estimated total cost in USD. */
  estimated_cost: number;
  /** Preparation time in minutes (chopping, measuring, etc.). */
  prep_time_min: number;
  /** Cooking time in minutes (active cooking / baking). */
  cook_time_min: number;
  /** Subjective difficulty rating. */
  difficulty: 'easy' | 'medium' | 'hard';
  /**
   * Which meal slots this meal is suitable for.
   * Stored as `text[]` in Postgres. A meal can be appropriate for multiple slots
   * (e.g. a smoothie might be both breakfast and snack).
   */
  meal_type: MealSlotType[];
  /** Free-form tags for filtering (e.g. `['quick', 'vegetarian']`). */
  tags: string[];
  /** True if this meal was generated by the Gemini AI. */
  is_ai_generated: boolean;
  /** ISO 8601 timestamp — set by the database on insert. */
  created_at: string;
}

/**
 * The four meal slots available for each calendar day.
 * Used as both a slot identifier and a value in `Meal.meal_type`.
 */
export type MealSlotType = 'breakfast' | 'lunch' | 'dinner' | 'snack';

/**
 * A meal assigned to a specific slot on a specific date.
 * Rows in `meal_plan_items` are keyed on `(user_id, date, slot)` — only one
 * meal can occupy a slot per day (enforced by an upsert conflict constraint).
 */
export interface MealPlanItem {
  /** UUID primary key. */
  id: string;
  /** UUID of the owning user. */
  user_id: string;
  /** UUID of the assigned meal. */
  meal_id: string;
  /** Calendar date in `YYYY-MM-DD` format. */
  date: string;
  /** Which meal slot this item occupies. */
  slot: MealSlotType;
  /** ISO 8601 timestamp — set by the database on insert. */
  created_at: string;
  /**
   * Joined meal data — populated when the query uses `select('*, meal:meals(*)')`.
   * Undefined in list queries that omit the join.
   */
  meal?: Meal;
}

/**
 * Input payload sent to the `generate-meal-plan` Supabase Edge Function.
 * Validated client-side by `generateMealPlanSchema` in `lib/validation.ts`
 * before the request is sent.
 */
export interface GenerateMealPlanRequest {
  /** Time horizon for the generated plan. */
  timeframe: 'day' | 'week' | 'month';
  /** Total budget in USD for the entire timeframe. */
  budget: number;
  /** Maximum acceptable total cook time per meal, in minutes. */
  max_cook_time: number;
  /** Number of servings each meal should yield. */
  servings: number;
  /** Optional daily calorie target (omit to let the AI decide). */
  daily_calories?: number;
  /** Dietary restrictions the AI must respect. */
  dietary_restrictions: DietaryRestriction[];
  /** Ingredients the user already has available (reduces cost). */
  available_ingredients: string[];
  /** User's cooking skill level — affects recipe complexity. */
  skill_level: string;
}

/**
 * A single meal returned by the Gemini AI in the edge function response.
 * Each `GeneratedMeal` is transformed into a `Meal` row when the user saves
 * their plan (see `app/(tabs)/generate.tsx` `handleSave`).
 */
export interface GeneratedMeal {
  /** Display name of the meal. */
  name: string;
  /** Short description. */
  description: string;
  /**
   * Which slot this meal is intended for.
   * Note: `GeneratedMeal.meal_type` is a single `MealSlotType`, but when
   * inserting into `meals` it is wrapped in an array (`[meal.meal_type]`)
   * because `Meal.meal_type` is `MealSlotType[]`.
   */
  meal_type: MealSlotType;
  /**
   * 1-based day index within the plan (1 = today/day 1).
   * For monthly plans split into 4 weekly calls, day offsets are adjusted by
   * `week * 7` before combining results.
   */
  day: number;
  /** Structured ingredient list. */
  ingredients: Ingredient[];
  /** Ordered cooking instructions. */
  instructions: InstructionStep[];
  /** Calories per serving. */
  calories: number;
  /** Protein in grams per serving. */
  protein_g: number;
  /** Carbohydrates in grams per serving. */
  carbs_g: number;
  /** Fat in grams per serving. */
  fat_g: number;
  /** Estimated total cost in USD. */
  estimated_cost: number;
  /** Preparation time in minutes. */
  prep_time_min: number;
  /** Cooking time in minutes. */
  cook_time_min: number;
  /** Subjective difficulty. */
  difficulty: 'easy' | 'medium' | 'hard';
  /** Free-form tags. */
  tags: string[];
}
